thread_ID, Id, ParentId, PostType, Score, CreationDate, OwnerID, Body
30503207,30503207,null,1,3,Thu May 28 09:57:00 EDT 2015,2445538,"<p>I'm writing a Java application to publish/subscribe to Internet of Things MQTT server using the Eclipse Paho Lib (org.eclipse.paho.client.mqtt3-1.0.2.jar), both on Device and Application side.</p>		<p>Connect works well with both credential types, and same seems to be the publish... What gives me the error is the subscribe:</p>		<p>Trying it by mosquitto_sub command line, it loops like this:</p>		<pre><code>Client a:u5o0ux:tws sending CONNECT	Client a:u5o0ux:tws received CONNACK	Client a:u5o0ux:tws sending SUBSCRIBE (Mid: 1, Topic: matteo, QoS: 0)	Client a:u5o0ux:tws sending CONNECT	Client a:u5o0ux:tws received CONNACK	Client a:u5o0ux:tws sending SUBSCRIBE (Mid: 2, Topic: matteo, QoS: 0)	Client a:u5o0ux:tws sending CONNECT	Client a:u5o0ux:tws received CONNACK	Client a:u5o0ux:tws sending SUBSCRIBE (Mid: 3, Topic: matteo, QoS: 0)	Client a:u5o0ux:tws sending CONNECT	Client a:u5o0ux:tws received CONNACK	Client a:u5o0ux:tws sending SUBSCRIBE (Mid: 4, Topic: matteo, QoS: 0)	...	</code></pre>		<p>And so on.</p>		<p>When trying from java with an MqttAsyncClient, the subcribe() method returns, but then the waitForCompletion() method istantly trows:</p>		<pre><code>Connection lost (32109) - java.io.EOFException	</code></pre>		<p>This is the code I am running:</p>		<pre><code>String tmpDir = System.getProperty("java.io.tmpdir");	MqttDefaultFilePersistence dataStore = new MqttDefaultFilePersistence(tmpDir); 		...		// Construct a non blocking MQTT client instance	client = new MqttAsyncClient(getMQTTBrokerURL(), clientId, dataStore);		// Set this wrapper as the callback handler	client.setCallback(this);	</code></pre>		<p>and then:</p>		<pre><code>connect();		...		IMqttToken subToken = client.subscribe(topic, qos, null, null);	subToken.waitForCompletion();	</code></pre>		<p>Also, this error makes the lib to not relese the persistence path user by the AsyncClient, making it to trow a "Persistence Already in Use" exception on every retry, until I stop the JVM and manually clear that path, but i suppose this to be some sort of library bug.</p>		<p>Unfortunately, I can't (or don't know how) access the IoT-side mqtt server to realize what's going on in there.</p>		<p>Any ideas? Thank you</p>	"
30503207,30507246,30503207,2,0,Thu May 28 12:56:00 EDT 2015,429431,"<p>If both mosquitto_sub and your Paho Java client are having problems at the same point (SUBSCRIBE), that implies the problem with your broker.</p>		<p>I tried running this:</p>		<pre><code>mosquitto_sub -t matteo -i 'a:u5o0ux:tws' -d -h test.mosquitto.org	</code></pre>		<p>And got the output:</p>		<pre><code>Client a:u5o0ux:tws sending CONNECT	Client a:u5o0ux:tws received CONNACK	Client a:u5o0ux:tws sending SUBSCRIBE (Mid: 1, Topic: matteo, QoS: 0)	Client a:u5o0ux:tws received SUBACK	Subscribed (mid: 1): 0	</code></pre>		<p>Maybe you could try connecting your client to <code>test.mosquitto.org</code>, <code>iot.eclipse.org</code> or one of the other public MQTT brokers out there. Or you could run your own copy of a broker locally for testing.</p>	"
30503207,30596378,30503207,2,2,Tue Jun 02 12:39:00 EDT 2015,4454969,"<p>It appears your problem is likely due to invalid topic "matteo". </p>		<p>For connecting to the IoT Foundation in Bluemix, you will need to follow the topic format as outlined in the IBM Internet of Things Foundation documentation here: 	<a href="https://docs.internetofthings.ibmcloud.com/messaging/applications.html" rel="nofollow">https://docs.internetofthings.ibmcloud.com/messaging/applications.html</a></p>	"
30503207,52217070,30596378,3,0,Sun Aug 23 09:17:00 EDT 2015,1655394,"Thank You! Solved my problem."
