thread_ID, Id, ParentId, PostType, Score, CreationDate, OwnerID, Body
33058114,33058114,null,1,1,Sat Oct 10 19:30:00 EDT 2015,2361432,"<p>I just try to connect to my Bluemix IOT Foundation instance with a mosquitto mqtt client. I configured everything as described in <a href="https://docs.internetofthings.ibmcloud.com/messaging/devices.html" rel="nofollow">https://docs.internetofthings.ibmcloud.com/messaging/devices.html</a>. My python client connects but disconnect after a second. </p>		<pre><code>import paho.mqtt.client as mqtt		def on_connect(client, userdata, flags, rc):	    print("Connected with result code "+str(rc))	    client.subscribe("$SYS/#")		def on_disconnect(client, userdata, rc):	print("Disconnect with result code "+str(rc))		def on_message(client, userdata, msg):	    print(msg.topic+" "+str(msg.payload))		client = mqtt.Client(client_id="d:gixu3a:RaspberryPi:abcdefgh")		client.on_connect    = on_connect	client.on_message    = on_message	client.on_disconnect = on_disconnect		client.username_pw_set("use-token-auth", password="XXXXXXX")		client.connect("gixu3a.messaging.internetofthings.ibmcloud.com", 1883, 60)		client.loop_forever()	</code></pre>		<p>Return code when I get disconnected is 1 and I can also see the connection inside the IOT Foundation dashboard:</p>		<pre><code>Connection State	Disconnected on Saturday, October 10, 2015 at 9:10:22 PM from 89.140.177.130 	with an insecure connection Refresh	</code></pre>		<p>Can I get any logfile from the Bluemix side?</p>	"
33058114,53988116,33058114,3,0,Mon Oct 12 16:27:00 EDT 2015,4454969,"Are you still experiencing the same error today?  There was some restructuring of DNS records that possibly affected your connection, but if that was the cause you should be back to working normally now."
33058114,33235865,33058114,2,1,Tue Oct 20 11:49:00 EDT 2015,1510113,"<p>It is because it is not accepting the topic as valid - devices can only subscribe to commands - try subscribing to something like "iot-2/cmd/acommand/fmt/json" </p>	"
