thread_ID, Id, ParentId, PostType, Score, CreationDate, OwnerID, Body
40889889,40889889,null,1,0,Wed Nov 30 13:40:00 EST 2016,7231078,"<p>I'm not able fetch sensor data uploaded to a Cloudant NoSQL DB through the IoT Platform using the sync-android library for some reason. </p>		<p>Please find the code, the error message and the line where the error is occurring below:</p>		<pre><code>try {	    uri = new URI("https://user:password@somehost.cloudant.com/database");	} catch (URISyntaxException e) {	    e.printStackTrace();	}	try {	    ds = manager.openDatastore("my_datastores");	} catch (DatastoreNotCreatedException e) {		            }	Replicator replicator = ReplicatorBuilder.pull().from(uri).to(ds).build();	Log.e("aaaaa",String.valueOf(replicator));	CountDownLatch latch = new CountDownLatch(1);	Listener listener = new Listener(latch);	Toast.makeText(MainActivity.this,String.valueOf(listener),Toast.LENGTH_LONG).show();	replicator.getEventBus().register(listener);	replicator.start();	try {	    latch.await();	} catch (InterruptedException e) {	    e.printStackTrace();	}	replicator.getEventBus().unregister(listener);	if (replicator.getState() != Replicator.State.COMPLETE) {	    System.out.println("Error replicating FROM remote");	    System.out.println(listener.error);	}	</code></pre>		<p>Error:</p>		<pre><code>Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.cloudant.sync.datastore.Datastore com.cloudant.sync.datastore.DatastoreManager.openDatastore(java.lang.String)' on a null object reference	                                                                                      at com.example.imb_bng_04.cloudserver.MainActivity.onCreate(MainActivity.java:42)	</code></pre>		<p>error in line:	   ds = manager.openDatastore("my_datastores");</p>	"
40889889,68993721,40889889,3,0,Wed Nov 30 13:49:00 EST 2016,4923755,"I removed the credentials from the URL. Make sure you do that yourself in future questions."
40889889,40890871,40889889,2,1,Wed Nov 30 14:27:00 EST 2016,4454969,"<p>Looks like maybe you are getting null pointer because you did not initialize an object.  See this S<a href="https://stackoverflow.com/questions/22329029/java-lang-nullpointerexception-attempt-to-invoke-virtual-method-android-view-v">tack overflow post</a> which has similar error.  </p>	"
40889889,40890980,40889889,2,1,Wed Nov 30 14:32:00 EST 2016,212858,"<pre><code>Caused by: java.lang.NullPointerException:	</code></pre>		<p>something was null</p>		<pre><code>Attempt to invoke virtual method	  'com.cloudant.sync.datastore.Datastore com.cloudant.sync.datastore.DatastoreManager	  ...openDatastore(java.lang.String)'	on a null object reference	</code></pre>		<p>so the thing that was null was the object you called <code>openDatastore</code> on</p>		<pre><code>at com.example.imb_bng_04.cloudserver.MainActivity.onCreate(MainActivity.java:42)	</code></pre>		<p>on this particular line:</p>		<pre><code>ds = manager.openDatastore("my_datastores");	</code></pre>		<p>So, what is this object reference, on which we called <code>openDatastore</code>, and which turned out to be null?</p>		<p>It was <code>manager</code>, very obviously. The variable <code>manager</code> is null. You haven't shown where it comes from, so no-one can possibly help tell you <em>why</em> it is null, but your fix consists of figuring that out, initializing it to something sensible, and then not calling methods on a null object reference.</p>	"
