thread_ID, Id, ParentId, PostType, Score, CreationDate, OwnerID, Body
49046137,49046137,null,1,0,Thu Mar 01 09:05:00 EST 2018,9427967,"<p>root@honeypot:~/telnet-iot-honeypot# python backend.py</p>		<p>Creating/Connecting to DB	DB Setup done	 * Running on <a href="http://0.0.0.0:5000/" rel="nofollow noreferrer">http://0.0.0.0:5000/</a> (Press CTRL+C to quit)	^C</p>		<p>root@honeypot:~/telnet-iot-honeypot# python honeypot.py</p>		<p>2018-03-01 08:50:39   telnet.py:57      Socket open on port 23	2018-03-01 08:50:57   telnet.py:72      Client connected at ('[REDACTED]', 59542)	2018-03-01 08:50:57   session.py:22     New Session	Traceback (most recent call last):</p>		<pre><code> File "/root/telnet-iot-honeypot/honeypot/telnet.py", line 75, in handle	 sess.loop()	 File "/root/telnet-iot-honeypot/honeypot/telnet.py", line 96, in loop	 self.session = Session(self.send_string, self.remote[0])	 File "/root/telnet-iot-honeypot/honeypot/session.py", line 26, in __init__	 self.record      = SessionRecord()	  File "/root/telnet-iot-honeypot/honeypot/sampledb_client.py", line 51, in __init__	self.back    = get_backend()	File "/root/telnet-iot-honeypot/honeypot/sampledb_client.py", line 14, in      get_backend	if _BACKEND:	</code></pre>		<p>UnboundLocalError: local variable '_BACKEND' referenced before assignment</p>		<p><a href="https://github.com/Phype/telnet-iot-honeypot" rel="nofollow noreferrer">https://github.com/Phype/telnet-iot-honeypot</a>	This honeypot is used to monitor port 23 or 2223 for incoming connections. I am getting this error whenever a client connects. How do I fix this? </p>	"
49046137,85098751,49046137,3,0,Thu Mar 01 10:05:00 EST 2018,9427967,"I get: root@honeypot:~/telnet-iot-honeypot# python honeypot.py           	Traceback (most recent call last):	  File "honeypot.py", line 6, in <module>	    from honeypot.telnet      import Telnetd	  File "/root/telnet-iot-honeypot/honeypot/telnet.py", line 6, in <module>	    from session import Session	  File "/root/telnet-iot-honeypot/honeypot/session.py", line 13, in <module>	    from sampledb_client import SessionRecord	  File "/root/telnet-iot-honeypot/honeypot/sampledb_client.py", line 18	    elif config.get("backend", optional=True) != None:	       ^	SyntaxError: invalid syntax"
49046137,85098781,49046137,3,0,Thu Mar 01 10:06:00 EST 2018,9427967,"I get this new error when I change the sampledb_client.py in 	github.com/Phype/telnet-iot-honeypot/issues/11"
49046137,85097895,49046137,3,0,Thu Mar 01 09:40:00 EST 2018,8085234,"https://github.com/Phype/telnet-iot-honeypot/issues/11"
49046137,85102539,49046137,3,0,Thu Mar 01 11:56:00 EST 2018,8085234,"The suggested fix for that specific issue would be to replace `tree = parse(l)` with `tree = run(l)` inside session.py"
49046137,85119302,49046137,3,0,Thu Mar 01 19:33:00 EST 2018,9427967,"I'm still getting the error above about the syntax error even when i change the session.py file correctly."
